# Generated by Django 6.1.1 on 2026-09-12 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('MISSING_IN_SYSTEM_B', 'Missing in System B'), ('ORPHAN_IN_SYSTEM_B', 'Orphan in System B'), ('DUPLICATE_IN_SYSTEM_B', 'Duplicate in System B'), ('VALUE_MISMATCH', 'Value Mismatch')], db_index=True, max_length=30)),
                ('record_id', models.CharField(max_length=100)),
                ('location_id', models.CharField(blank=True, default='', max_length=50)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('system_a_value', models.CharField(blank=True, max_length=200, null=True)),
                ('system_b_value', models.CharField(blank=True, max_length=200, null=True)),
                ('field_name', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'discrepancies',
                'ordering': ['org_id', 'reason', 'record_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('org_id', models.CharField(db_index=True, max_length=50)),
                ('org_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('normalized_id', models.CharField(db_index=True, max_length=50)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('raw_data', models.TextField(blank=True, default='{}')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_a_records', to='reconciler.location')),
            ],
            options={
                'db_table': 'system_a_records',
            },
        ),
        migrations.CreateModel(
            name='SystemBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_b_id', models.CharField(max_length=50, unique=True)),
                ('record_ref', models.CharField(max_length=100)),
                ('normalized_ref', models.CharField(db_index=True, max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('raw_data', models.TextField(blank=True, default='{}')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_b_records', to='reconciler.location')),
            ],
            options={
                'db_table': 'system_b_records',
            },
        ),
    ]
